name: ci-api-go-rest

on:
  push:
    branches: [main]

jobs:
  ci-api-go-rest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
      - name: Build and push Docker Hub
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          tags: |
            albertosouzafernandes/api-go-rest:v1.2

  cd-api-go-rest:
    runs-on: self-hosted
    steps:
      - name: Atualize o pod com nova imagem
        run: kubectl run api-go-rest --image=albertosouzafernandes/api-go-rest:v1.2 --port=8000  --env="DB_USUARIO=${{secrets.DB_USUARIO}}" --env="DB_SENHA=${{secrets.DB_SENHA}}" --env="DB_HOST=${{secrets.DB_HOST}}" --env="DB_DATABASE=${{secrets.DB_DATABASE}}" 
          

      
